version: '3.4'

services:
  loginapp:
    ports:
      - "80"
    restart: always
    depends_on:  
      - sqlserverService 
    networks:
      - loginappNetwork
    build:
      context: .
      dockerfile: Dockerfile

  sqlserverService:  
    image: microsoft/mssql-server-linux:2017-latest  
    hostname: 'sqlserver'  
    restart: always
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "reallyStrongPwd123"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '1433'  
    expose:  
      - 1433 
    networks:
      - loginappNetwork
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - loginapp
      - sqlserverService
    ports:
      - "4000:4000" 
    networks:
      - loginappNetwork      


networks:
  loginappNetwork: {}      